### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by iwpdesigns** [Codeinwp/Zerius#28]
I just added the zerius child theme and logo doesn't work. You can change it in customizer but will not show?

**Comment by poonam279** [comment]
@rodica-andronache this is a bug when we add a logo from customizer it does not show on front page.

**Comment by suyogyashukla** [comment]
You need to replace the header.php of child theme with that of parent theme for it to work, since we made some changes.

**Comment by rodica-andronache** [comment]
Hi @iwpdesigns ,

There were some changes made in the parent theme, and because we couldn't update the child theme (because many users make changes directly there ) there are some issues, like the one you mentioned. To fix that, you need to follow this doc http://docs.themeisle.com/article/572-how-to-fix-the-logo-issue-in-responsiveboat-when-using-zerif-pro, even though it's referring to another child theme. It should work the same.
So, please try to do that, instead of replacing the header.php file with the one from the parent theme and let me know if that helps.

Regards,
Rodica
